version: '3.8'

services:
  app:
    build: .
    container_name: email_confirmation_app
    volumes:
      - .:/app
    networks:
      - email_confirmation_network

  mailpit:
    image: 'axllent/mailpit:v1.22.0'
    ports:
      - '${FORWARD_MAILPIT_PORT:-1025}:1025'
      - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
    networks:
      - email_confirmation_network

networks:
  email_confirmation_network: