version: '3.8'

services:
  app:
    build: .
    container_name: email_confirmation_app
    ports:
      - "8081:8081"
    volumes:
      - .:/app
    networks:
      - email_confirmation_network
    depends_on:
      - postgres
      - mailpit

  postgres:
    container_name: email_confirmation_postgres
    image: postgres:16.4
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-my_pass}
      POSTGRES_DB: ${POSTGRES_DB:-email_confirmation}
      PGDATA: /data/postgres
    volumes:
      - ./postgres-data:/data/postgres
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    networks:
      - email_confirmation_network

  mailpit:
    container_name: email_confirmation_mailpit
    image: 'axllent/mailpit:v1.22.0'
    ports:
      - '${FORWARD_MAILPIT_PORT:-1025}:1025'
      - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
    networks:
      - email_confirmation_network

networks:
  email_confirmation_network: